In [1]:
import numpy as np
import pandas as pd
import sys
import os
import sqlite3
sys.path.append('/ubc/ece/home/ra/grads/siyi/Research/skin_lesion_segmentation/skin-lesion-segmentation-transformer')

In [170]:
'''isic2018'''
data_folder = '/bigdata/siyiplace/data/skin_lesion'
isic2018_meta = data_folder+'/2018_raw_data/train_test_id.csv'
df = pd.read_csv(isic2018_meta)
print(len(df))

2594

In [171]:
diagnosis_list = []
ID_list = []
for i in range(len(df)):
    diagnosis_list.append(df.iloc[i]['Class'].capitalize())
    ID_list.append(df.iloc[i]['ID'].split('_')[1])
df['diagnosis'] = diagnosis_list
df['dataset'] = ['isic2018']*len(df)
df['ID'] = ID_list
df['diagnosis_id'] = df['diagnosis'].astype('category').cat.codes

In [172]:
df

,ID,Class,Split,W,H,pigment_network,negative_network,streaks,milia_like_cyst,globules,all,diagnosis,dataset,diagnosis_id,DC_id,four_id
0,0000164,melanoma,train,638,959,1,0,0,0,0,1,Melanoma,isic2018,0,0,0
1,0001148,melanoma,train,2304,3072,1,0,0,0,0,1,Melanoma,isic2018,0,0,1
2,0013258,melanoma,train,2000,3008,1,0,0,0,0,1,Melanoma,isic2018,0,0,2
3,0014189,melanoma,train,2848,4288,1,0,0,1,0,2,Melanoma,isic2018,0,0,3
4,0013457,melanoma,train,2848,4288,0,0,0,1,0,1,Melanoma,isic2018,0,0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2589,0014503,seborrheic_keratosis,test,2848,4288,0,0,0,1,0,1,Seborrheic_keratosis,isic2018,2,2,2589
2590,0012358,seborrheic_keratosis,test,2000,3008,0,0,0,0,0,0,Seborrheic_keratosis,isic2018,2,2,2590
2591,0013333,seborrheic_keratosis,test,2848,4288,0,0,0,0,0,0,Seborrheic_keratosis,isic2018,2,2,2591
2592,0012693,seborrheic_keratosis,test,2000,3008,0,0,0,0,0,0,Seborrheic_keratosis,isic2018,2,2,2592
2593,0014580,seborrheic_keratosis,test,1936,2592,0,0,0,1,0,1,Seborrheic_keratosis,isic2018,2,2,2593

In [173]:
df['DC_id'].value_counts()

1    1867
0     519
2     208
Name: DC_id, dtype: int64

In [135]:
df.to_csv(data_folder+'/isic2018/meta_isic2018.csv', index=False)

In [174]:
'''PH2'''
data_folder = '/bigdata/siyiplace/data/skin_lesion'
PH2_meta = data_folder+'/PH2_rawdata/PH2Dataset/PH2_dataset.xlsx'
df = pd.read_excel(PH2_meta, skiprows=range(12))
print(len(df))

200

In [175]:
diagnosis_list = []
for i in range(len(df)):
    row = df.iloc[i]
    for diag_name in ['Common Nevus', 'Atypical Nevus', 'Melanoma']:
        if row[diag_name] == 'X':
            diagnosis_list.append(diag_name)
            break
    else:
        print(i)
df['diagnosis'] = diagnosis_list
df['dataset'] = ['PH2']*len(df)
df['ID']=df['Image Name']
df['diagnosis_id'] = df['diagnosis'].astype('category').cat.codes

In [176]:
df

,Image Name,Histological Diagnosis,Common Nevus,Atypical Nevus,Melanoma,Asymmetry\n(0/1/2),Pigment Network\n(AT/T),Dots/Globules\n(A/AT/T),Streaks\n(A/P),Regression Areas\n(A/P),...,Light-Brown,Dark-Brown,Blue-Gray,Black,diagnosis,dataset,ID,diagnosis_id,DC_id,four_id
0,IMD003,NaN,X,NaN,NaN,0,T,A,A,A,...,NaN,X,NaN,NaN,Common Nevus,PH2,IMD003,1,4,2594
1,IMD009,NaN,X,NaN,NaN,0,T,A,A,A,...,X,NaN,NaN,NaN,Common Nevus,PH2,IMD009,1,4,2595
2,IMD016,NaN,X,NaN,NaN,0,T,T,A,A,...,X,X,NaN,NaN,Common Nevus,PH2,IMD016,1,4,2596
3,IMD022,NaN,X,NaN,NaN,0,T,A,A,A,...,X,NaN,NaN,NaN,Common Nevus,PH2,IMD022,1,4,2597
4,IMD024,NaN,X,NaN,NaN,0,T,A,A,A,...,X,X,NaN,NaN,Common Nevus,PH2,IMD024,1,4,2598
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,IMD424,Melanoma,NaN,NaN,X,2,AT,AT,P,A,...,X,X,X,X,Melanoma,PH2,IMD424,2,5,2789
196,IMD425,Melanoma,NaN,NaN,X,2,AT,AT,A,P,...,X,X,X,X,Melanoma,PH2,IMD425,2,5,2790
197,IMD426,Melanoma,NaN,NaN,X,2,AT,A,A,P,...,X,X,NaN,NaN,Melanoma,PH2,IMD426,2,5,2791
198,IMD429,NaN,NaN,NaN,X,0,AT,A,P,A,...,X,X,X,X,Melanoma,PH2,IMD429,2,5,2792
199,IMD435,Lentigo Maligna,NaN,NaN,X,2,AT,A,A,A,...,X,X,X,X,Melanoma,PH2,IMD435,2,5,2793

In [157]:
df.to_csv(data_folder+'/PH2/meta_PH2.csv',index=False)

In [5]:
'''DMF'''
data_folder = '/bigdata/siyiplace/data/skin_lesion'
DMF_meta = data_folder+'/DMF_origin/meta-dmf.csv'
df = pd.read_csv(DMF_meta)
print(len(df))

1212

In [179]:
df['dataset']=['DMF']*len(df)
diagnosis_list = []
ID_list = []
for i in range(len(df)):
    path = df.iloc[i]['path']
    ID_list.append(path.split('/')[1])
    diagnosis_list.append(df.iloc[i]['dx'].title())
df['ID']=ID_list
df['diagnosis'] = diagnosis_list
df['diagnosis_id'] = df['diagnosis'].astype('category').cat.codes

In [3]:
df

,path,lesion_id,ori_dx,dx,dx_idx,dom
0,images/D204a/D204a.png,1,BCC,Basal cell carcinoma,2,dmf
1,images/D226b/D226b.png,3,ML,Melanocytic nevi,1,dmf
2,images/D226c/D226c.png,4,ML,Melanocytic nevi,1,dmf
3,images/D227/D227.png,5,ML,Melanocytic nevi,1,dmf
4,images/D231/D231.png,6,AK,Actinic keratoses,3,dmf
...,...,...,...,...,...,...
1207,images/D649a/D649a.png,1296,IEC,Actinic keratoses,3,dmf
1208,images/G40a/G40a.png,1297,IEC,Actinic keratoses,3,dmf
1209,images/P100/P100.png,1298,IEC,Actinic keratoses,3,dmf
1210,images/T239/T239.png,1299,IEC,Actinic keratoses,3,dmf
1211,images/T39/T39.png,1300,IEC,Actinic keratoses,3,dmf

In [181]:
df['DC_id'].value_counts()

10    331
8     257
7     239
6     123
12    121
11     76
9      65
Name: DC_id, dtype: int64

In [162]:
df.to_csv(data_folder+'/DMF/meta_DMF.csv', index=False)

In [189]:
'''SKD
create meta file'''
data_folder = '/bigdata/siyiplace/data/skin_lesion'
melanoma_folder = data_folder+'/skin_cancer_detection_origin/skin_image_data_set-1/Skin Image Data Set-1/skin_data/melanoma'
benign_folder = data_folder+'/skin_cancer_detection_origin/skin_image_data_set-2/Skin Image Data Set-2/skin_data/notmelanoma'
image_name_list = []
diagnosis_list = []

for dataset_name in ['dermis', 'dermquest']:
    path_list = os.listdir('{}/{}'.format(melanoma_folder, dataset_name))
    for path in path_list:
        if path[-4:] == '.jpg':
            image_name = dataset_name+'_'+path[:-4]
            image_name_list.append(image_name)

diagnosis_list.extend(['Melanoma']*len(image_name_list))

count = 0
for dataset_name in ['dermis', 'dermquest']:
    path_list = os.listdir('{}/{}'.format(benign_folder, dataset_name))

    for path in path_list:
        if path[-4:] == '.jpg':
            image_name = dataset_name+'_'+path[:-4]
            image_name_list.append(image_name)
            count += 1

diagnosis_list.extend(['Benign']*count)

In [190]:
print(len(diagnosis_list))
print(len(image_name_list))
SKD_meta_path = data_folder+'/SKD/meta_SKD.csv'
df = pd.DataFrame({
    'dataset': ['SKD']*len(diagnosis_list),
    'ID': image_name_list,
    'diagnosis': diagnosis_list,
})
df.to_csv(SKD_meta_path, index=False)

206
206

In [191]:
SKD_meta_path = data_folder+'/SKD/meta_SKD.csv'
SKD_meta = pd.read_csv(SKD_meta_path)
# SKD_meta

In [192]:
df['diagnosis_id'] = df['diagnosis'].astype('category').cat.codes

In [193]:
df

    dataset                   ID diagnosis  diagnosis_id  DC_id  four_id
0       SKD     dermis_AMM1_orig  Melanoma             1     14     4006
1       SKD     dermis_LMM1_orig  Melanoma             1     14     4007
2       SKD     dermis_LMM2_orig  Melanoma             1     14     4008
3       SKD     dermis_LMM4_orig  Melanoma             1     14     4009
4       SKD     dermis_LMM5_orig  Melanoma             1     14     4010
..      ...                  ...       ...           ...    ...      ...
201     SKD    dermquest_D6_orig    Benign             0     13     4207
202     SKD  dermquest_D8_2_orig    Benign             0     13     4208
203     SKD    dermquest_D8_orig    Benign             0     13     4209
204     SKD  dermquest_D9_2_orig    Benign             0     13     4210
205     SKD    dermquest_D9_orig    Benign             0     13     4211

[206 rows x 6 columns]

In [195]:
df.to_csv(SKD_meta_path, index=False)